1412 task3 secure web api with authenticationand authorization
MuhammadFaizanGulzar/TrainingTestPool pull request #2
Opened 2023-10-13 10:30 UTC by MuhammadFaizanGulzar

2023-10-13 11:06 UTC, taimoor0nline commented on CRUD.Domain/Models/AuthResponse.cs
> +        public string? Token { get; set; }
why token and message are nullable?

2023-10-13 11:07 UTC, taimoor0nline commented on CRUD.Domain/Class1.cs
> +{
remove this class if you are not using it

2023-10-13 11:07 UTC, taimoor0nline commented on CRUD.Application/Class1.cs
> +    {
remove this class if you are not using it

2023-10-13 11:09 UTC, taimoor0nline commented on CRUD.Domain/Models/Authentication/Login.cs
> +
Please remove it if you are not using it

2023-10-13 11:09 UTC, taimoor0nline commented on CRUD.Domain/Models/Authentication/SignUp.cs
> +    public class SignUp
Please remove it if you are not using it

2023-10-13 11:09 UTC, taimoor0nline commented on CRUD.Domain/Models/LoginRequest.cs
> +        public string? username { get; set; }
why the user and password are nullable?

2023-10-13 11:10 UTC, taimoor0nline commented on CRUD.Domain/Models/RegisterUser.cs
> +
you have marked it as nullable and marking it as required as well ?

2023-10-13 11:10 UTC, taimoor0nline commented on CRUD.Domain/Models/Response.cs
> +        public string? Status { get; set; }
response should not be nullable there should be status and message

2023-10-13 11:11 UTC, taimoor0nline commented on CRUD.Domain/Models/Role.cs
> +        public int? Id { get; set; }
Please fix these nullable, should ID be nullable?

2023-10-13 11:11 UTC, taimoor0nline commented on CRUD.Domain/Models/User.cs
> +        public string? Email { get; set; }
fix nullable email

2023-10-13 11:15 UTC, taimoor0nline requested changes
Please review and fix code

2023-10-16 05:56 UTC, Gulzaib83 commented on WebApiCRUD/Controllers/TodoItemController.cs
> +            if (userRoles.Contains("Admin") || (userRoles.Contains("User") && todo.UserId == userId))
You should implement a middleware to implement the logic "One user should only perform CRUD over its own ToDos". If a particular Todo is not under ownership of a user then it Middleware should intercept this call and it should not reach the Controller"

2023-10-16 05:56 UTC, Gulzaib83 commented on WebApiCRUD/appsettings.json
> +    "DefaultConnection": "Server=.;Database=CRUD;TrustServerCertificate=True;Integrated Security=true; MultipleActiveResultSets=true"
See if you can implement "Options" design pattern for DB ConnectionString and JWT key.

2023-12-12 07:50 UTC, closed without merging